openapi: 3.1.0
info:
  title: Subtitle API
  version: "1.0.0"
  description: API that generates SRT/VTT/Text from an uploaded file URL for GPTs Custom Actions.
servers:
  - url: https://subtitle-maker.vercel.app
paths:
  /api/transcribe:
    post:
      operationId: transcribeVideo
      summary: Transcribe a video/audio file from a temporary URL and return subtitles
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [file_url]
              properties:
                file_url:
                  type: string
                  format: uri
                  description: Signed URL to the uploaded media file
                output_format:
                  type: string
                  enum: [srt, vtt, text]
                  default: srt
                language:
                  type: string
                  description: BCP-47 language code (e.g. "ja")
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  format: { type: string, enum: [srt, vtt, text] }
                  text_preview: { type: string }
                  srt: { type: string }
                  vtt: { type: string }
                  text: { type: string }
        "401": { description: Unauthorized }
        "422": { description: Bad Request }
        "500": { description: Internal Server Error }
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas: {}
